# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
# print version of numpy
print(np.__version__)

2.2.4


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
# create null vector numpy
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
bytes = null_vector.size * null_vector.itemsize
print(f"Size of the array: {bytes} bytes")

Size of the array: 80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
arr = np.arange(50)
arr = arr[::-1]
arr

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
arr = np.arange(9).reshape(3, 3)
arr




array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])
arr[arr != 0]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
arr = np.random.random((3, 3, 3))
arr

array([[[0.69335701, 0.00908456, 0.2403822 ],
        [0.50607998, 0.22943054, 0.38241026],
        [0.56556767, 0.18075063, 0.54808413]],

       [[0.84378149, 0.13654412, 0.2863688 ],
        [0.58900029, 0.25136773, 0.16862401],
        [0.14362221, 0.76735462, 0.09459916]],

       [[0.22426717, 0.55967135, 0.50165739],
        [0.78515833, 0.99222899, 0.16060758],
        [0.45673623, 0.88952091, 0.86237284]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
arr = np.random.random((10, 10))
arr.min(), arr.max()

(np.float64(0.0013723407184224046), np.float64(0.9891335164480023))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
arr = np.random.random(30)
arr.mean(), arr.std()

(np.float64(0.41747461114893125), np.float64(0.24786531929409736))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [29]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [30]:
arr = np.ones((5, 5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# 0 * np.nan = np.nan
# np.nan == np.nan = False
# np.inf > np.nan = False
# np.nan - np.nan = np.nan
# np.nan in np.array([np.nan]) = True
# 0.3 == 3 * 0.1 = True

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [47]:
diag = np.diag(np.arange(1, 5), k=-1)
diag

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [50]:
arr = np.zeros((8, 8), dtype=int)
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [54]:
arr = np.arange(6 * 7 * 8).reshape(6, 7, 8)
print(arr.shape)
ind = np.unravel_index(99, arr.shape)
print(ind)
print(arr[ind])

(6, 7, 8)
(np.int64(1), np.int64(5), np.int64(3))
99


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [55]:
arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [57]:
arr = np.random.random((5, 5))
arr = (arr - arr.mean()) / arr.std()
arr

array([[ 0.44794075, -0.01706247, -0.03573887, -0.63113463,  1.44417368],
       [ 1.3479811 , -1.9602251 ,  0.25945394,  0.69564996, -0.8481714 ],
       [-1.68486652, -1.58054732, -0.85534134, -1.22825956, -0.59743545],
       [ 0.26721063,  1.06635391,  1.11937517, -0.21471475, -1.06006519],
       [ 0.61124322,  0.45797655,  0.62508088,  1.31405294,  1.05706983]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [58]:
np.dtype([("r", np.ubyte, 1),
          ("g", np.ubyte, 1),
          ("b", np.ubyte, 1),
          ("a", np.ubyte, 1)])


dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [59]:
arr_5_3 = np.random.random((5, 3))
arr_3_2 = np.random.random((3, 2))
arr_5_3 @ arr_3_2

array([[0.23061352, 0.35278057],
       [0.58567839, 1.2156224 ],
       [0.80232197, 1.47580081],
       [0.55745503, 1.13957171],
       [0.54757727, 1.11123868]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [60]:
arr = np.arange(10)
arr[3:8] *= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [63]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [73]:
Z = np.arange(5)
print(Z ** Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j * Z)
print(Z / 1 / 1)
print(Z < Z)


[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]
[False False False False False]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [82]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/8g/x9ncyhjj3wdchhjpvtkcr_640000gp/T/ipykernel_48334/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/8g/x9ncyhjj3wdchhjpvtkcr_640000gp/T/ipykernel_48334/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/8g/x9ncyhjj3wdchhjpvtkcr_640000gp/T/ipykernel_48334/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [86]:
arr = np.random.uniform(-10, 10, 10)
arr
print(np.copysign(np.ceil(np.abs(arr)), arr))

[ 8.  8.  9.  5. -9.  5.  1.  1. -7. -8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [123]:
num_iterations = 10000
total = 0
for i in range(num_iterations):
    arr1 = np.random.randint(0, 10, 10)
    arr2 = np.random.randint(0, 10, 10)
    intersection = np.intersect1d(arr1, arr2)
    if intersection.size > 0:
        total += 1
    if i % 10000 == 0:
        print(f"{i} iterations done")
print(total / num_iterations)

0 iterations done
0.9996


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [125]:
np.seterr(all='ignore')
np.errstate(divide='ignore')
print(0 / np.array(0))
print(np.array(0) / np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
nan
[0.]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [126]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [127]:
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D'))


2025-03-22
2025-03-21
2025-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [132]:
# month of jul 2016
month = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
month

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [133]:
A = np.ones(3) * 1
B = np.ones(3) * 2
# compute (A + B) * (-A / 2)
print(np.add(A, B, out=B))
print(np.divide(A, 2, out=A))
print(np.negative(A, out=A))
print(np.multiply(A, B, out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [135]:
arr = np.random.uniform(0, 10, 10)
print(arr)
print(arr - arr % 1)
print(np.floor(arr))
print(np.ceil(arr) - 1)
print(arr.astype(int))
print(np.trunc(arr))

[8.19637418 5.96680566 7.24896348 4.30200792 4.03330961 8.18969313
 7.16221247 0.26594682 1.41412991 9.83865291]
[8. 5. 7. 4. 4. 8. 7. 0. 1. 9.]
[8. 5. 7. 4. 4. 8. 7. 0. 1. 9.]
[8. 5. 7. 4. 4. 8. 7. 0. 1. 9.]
[8 5 7 4 4 8 7 0 1 9]
[8. 5. 7. 4. 4. 8. 7. 0. 1. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [136]:
arr = np.zeros((5, 5))
arr += np.arange(5)
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [141]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(), dtype=int)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [142]:
vec = np.linspace(0, 1, 11, endpoint=False)[1:]
vec

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [146]:
arr = np.random.random(10)
arr.sort()
arr

array([0.0709176 , 0.18613577, 0.2697777 , 0.41876508, 0.54293143,
       0.77057334, 0.79277401, 0.85568944, 0.85976719, 0.92260427])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [147]:
arr = np.random.random(10)
print(arr)
# sum faster than np.sum
print(np.add.reduce(arr))

[0.16605722 0.23121423 0.00235715 0.4587232  0.19085224 0.91405369
 0.7005831  0.62308957 0.23002188 0.28038612]
3.7973384046018333


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [171]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)
print(A, B)

False
[0 1 1 1 0] [1 0 1 0 1]


#### 43. Make an array immutable (read-only) (★★☆)

In [172]:
arr = np.random.random(10)
# make the array immutable
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [174]:
# random 10x2 matrix representing cartesian coordinates
arr = np.random.random((10, 2))
# convert to polar coordinates
X, Y = arr[:, 0], arr[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.87811958 0.90447218 0.44722648 1.14877674 0.60136417 0.2390522
 0.91213415 0.46228381 0.24369292 0.82361029]
[1.11399143 1.13334067 1.11819615 0.77398038 0.38782835 1.10248919
 0.89230823 0.81663572 0.33617067 0.14916682]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [176]:
vec = np.random.random(10)
print(vec)
vec[vec.argmax()] = 0
vec

[0.03960098 0.19242755 0.21999774 0.09110917 0.62509237 0.61637279
 0.97446048 0.07961168 0.94660203 0.48971034]


array([0.03960098, 0.19242755, 0.21999774, 0.09110917, 0.62509237,
       0.61637279, 0.        , 0.07961168, 0.94660203, 0.48971034])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [181]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [183]:
# contruct cauchy matrix given X and Y
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)


[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [184]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [186]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [187]:
vector = np.arange(100)
scalar = 4.2
# find the closest value to scalar in vector
index = (np.abs(vector - scalar)).argmin()
print(vector[index])

4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [188]:
# structured array with x and y coordinates and color (r, g, b)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))
 (([0.], [0.]), ([0.], [0.], [0.])) (([0.], [0.]), ([0.], [0.], [0.]))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [191]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
print(Z)

[[0.         0.37219458 0.25513224 0.45068011 0.80555218 0.4181992
  0.51672326 0.51244582 0.11900227 0.39679137]
 [0.37219458 0.         0.50331016 0.81741851 1.17773586 0.78772237
  0.88841286 0.81674673 0.45830915 0.76385707]
 [0.25513224 0.50331016 0.         0.51044592 0.78109893 0.38873662
  0.49586622 0.67890362 0.15589213 0.35521303]
 [0.45068011 0.81741851 0.51044592 0.         0.37920049 0.17396808
  0.15855722 0.27622908 0.41040246 0.20128986]
 [0.80555218 1.17773586 0.78109893 0.37920049 0.         0.40027211
  0.29313164 0.5748637  0.73504681 0.43067767]
 [0.4181992  0.78772237 0.38873662 0.17396808 0.40027211 0.
  0.10823593 0.43945137 0.33621037 0.03451617]
 [0.51672326 0.88841286 0.49586622 0.15855722 0.29313164 0.10823593
  0.         0.43263069 0.44195255 0.14075968]
 [0.51244582 0.81674673 0.67890362 0.27622908 0.5748637  0.43945137
  0.43263069 0.         0.53697164 0.45922291]
 [0.11900227 0.45830915 0.15589213 0.41040246 0.73504681 0.33621037
  0.44195255 0.536971

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [194]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[17 44  4 60 59 46 74 22 87 29]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [200]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int16)
Z

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int16)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [201]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [205]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
print(X, Y)
D = np.sqrt(X ** 2 + Y ** 2)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
G

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [204]:
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n * n), p, replace=False), 1)
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)